import {createClient} from '@sanity/client'

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production'
const token = process.env.SANITY_WRITE_TOKEN
const apiVersion = process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2026-07-09'

if (!projectId || !token) {
  console.error('Missing NEXT_PUBLIC_SANITY_PROJECT_ID or SANITY_WRITE_TOKEN')
  process.exit(1)
}

const client = createClient({projectId, dataset, token, apiVersion, useCdn: false})

const block = (text) => [{_type: 'block', style: 'normal', children: [{_type: 'span', text}]}]
const slug = (current) => ({_type: 'slug', current})

const docs = [
  {
    _id: 'siteSettings', _type: 'siteSettings', name: 'Dewanti Aisyah Legowo', role: 'Growth marketer with a story-driven and systems-minded point of view', siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://your-domain.com',
    colors: {primary:'#B85C38', secondary:'#8FA58E', background:'#F8F3EA', cardBackground:'#EFE3D3', text:'#252321', accent:'#2F4F5F'},
    defaultSeo: {metaTitle:'Dewanti Aisyah Legowo — Growth Marketing Portfolio', metaDescription:'A warm editorial portfolio about growth marketing, storytelling, analytics, geography, and AI-assisted workflows.', keywords:['growth marketing','portfolio','analytics','storytelling','AI workflows','geography']},
    personSchema: {jobTitle:'Growth Marketing Specialist', description:'A reflective growth marketer with a story-driven and systems-minded point of view.', sameAs:['https://dewantiaisyah.wordpress.com/']},
    socialLinks: [{label:'Email', url:'mailto:hello@example.com', isPrimary:true}, {label:'LinkedIn', url:'https://www.linkedin.com/', isPrimary:true}, {label:'Blog', url:'https://dewantiaisyah.wordpress.com/', isPrimary:false}]
  },
  {
    _id: 'homepage', _type: 'homepage', title:'Homepage',
    seo: {metaTitle:'Dewanti Aisyah Legowo — Growth Marketing Portfolio', metaDescription:'Portfolio of Dewanti Aisyah Legowo: growth marketing, storytelling, analytics, digital systems, and geography-informed strategic thinking.'},
    sections: [
      {_key:'hero', _type:'heroSection', isVisible:true, anchorId:slug('home'), backgroundStyle:'ivory', layout:'wide', eyebrow:'Pattern-reader. Story-builder. Growth-doer.', title:'My path has never been linear. But it has always been connected.', subtitle:'I started from art, movement, maps, places, and stories. Today, I bring that way of seeing into growth marketing: reading patterns, understanding people, building digital journeys, and turning ideas into systems that create measurable growth.', ctas:[{_key:'c1', _type:'cta', label:'View Projects', href:'#projects', style:'primary'}, {_key:'c2', _type:'cta', label:'View Experience', href:'#experience', style:'secondary'}, {_key:'c3', _type:'cta', label:'Contact Me', href:'#contact', style:'outline'}]},
      {_key:'about', _type:'richTextSection', isVisible:true, anchorId:slug('about'), backgroundStyle:'white', layout:'wide', eyebrow:'About', title:'I didn’t start from a typical marketing or tech background.', subtitle:'I started from art, movement, maps, places, and stories.', body:block('Since I was young, I’ve always been drawn to creative things: painting, dancing, observing details, and expressing ideas visually. Later, I studied Geography because I wanted to explore places, draw, and understand the world more closely. What I didn’t realize back then was that geography would become one of my strongest foundations. It trained me to see patterns, understand people in context, connect data with real places, and think in systems. Today, I bring that way of thinking into growth marketing.')},
      {_key:'thread', _type:'cardGridSection', isVisible:true, anchorId:slug('thread'), backgroundStyle:'sand', eyebrow:'The Thread Behind My Work', title:'My journey may look random from the outside. But each chapter has shaped the way I work today.', cards:[{_key:'a', title:'Art & Visual Sense', tag:'Observation', body:'Painting, dancing, and visual expression taught me how to notice details, compose ideas, and communicate beyond words.'}, {_key:'g', title:'Geography & Spatial Thinking', tag:'Context', body:'Geography trained me to understand people, places, movement, and systems. Data is never just numbers; it is connected to context.'}, {_key:'m', title:'Growth & Digital Marketing', tag:'Action', body:'Marketing became the place where creative, analytical, and strategic work met.'}, {_key:'ai', title:'Data, AI & Practical Tools', tag:'Expansion', body:'Now I explore AI-assisted workflows and practical tech tools to move faster from insight to action.'}]},
      {_key:'what', _type:'cardGridSection', isVisible:true, anchorId:slug('what-i-do'), backgroundStyle:'ivory', eyebrow:'What I Do', title:'I help turn scattered signals into clear growth actions.', subtitle:'My work sits at the intersection of growth strategy, performance marketing, storytelling, analytics, and systems.', cards:[{_key:'gs', title:'Growth Strategy', body:'Understanding goals, audiences, channels, and the journey needed to move people from awareness to action.'}, {_key:'pm', title:'Performance Marketing', body:'Planning, running, and optimizing paid campaigns across platforms like Meta and Google.'}, {_key:'cs', title:'Content & Storytelling', body:'Turning insights into messages, website copy, campaign narratives, and content that feels clear.'}, {_key:'as', title:'Analytics & Systems', body:'Using data, tracking, dashboards, and workflow tools to understand what works and what to improve.'}]},
      {_key:'projects', _type:'projectsSection', isVisible:true, anchorId:slug('projects'), backgroundStyle:'white', eyebrow:'Selected Work', title:'Selected Work', subtitle:'A few areas of work that show how strategy, message, audience, data, and execution connect.', showAllProjects:true},
      {_key:'experience', _type:'experienceSection', isVisible:true, anchorId:slug('experience'), backgroundStyle:'sand', eyebrow:'Experience', title:'Experience', subtitle:'Across these experiences, I learned that growth rarely comes from one channel alone.', showAllExperience:true},
      {_key:'skills', _type:'skillsSection', isVisible:true, anchorId:slug('capabilities'), backgroundStyle:'ivory', eyebrow:'Capabilities', title:'Capabilities', subtitle:'A practical mix of growth, content, analytics, product thinking, workflow, and creative production.', showAllSkills:true},
      {_key:'workview', _type:'richTextSection', isVisible:true, anchorId:slug('how-i-see-work'), backgroundStyle:'white', layout:'wide', eyebrow:'How I See Work', title:'I believe good work starts with paying attention.', body:block('Before building a campaign, writing a message, or analyzing a dashboard, we need to understand what is really happening: who we are speaking to, what they care about, what signals the data shows, and what context surrounds the decision.')},
      {_key:'geo', _type:'richTextSection', isVisible:true, anchorId:slug('geography'), backgroundStyle:'sand', layout:'wide', eyebrow:'Why Geography Still Matters', title:'A funnel is a kind of map.', body:block('A customer journey is a kind of movement. A campaign is a way of reaching people within a specific context. A dashboard is a way of seeing patterns across time and behavior. I do not see my path as a complete career switch. I see it as a translation: from maps to funnels, from places to platforms, from spatial patterns to user behavior.')},
      {_key:'build', _type:'richTextSection', isVisible:true, anchorId:slug('build'), backgroundStyle:'ivory', layout:'wide', eyebrow:'Now, I’m Expanding The Way I Build', title:'Learning tech is not about chasing trends. It is about expanding my ability to solve real problems.', body:block('Lately, I’ve been exploring data, AI-assisted workflows, and practical tech tools as a way to help marketers, researchers, and teams move faster from messy information to useful output.')},
      {_key:'writing', _type:'richTextSection', isVisible:true, anchorId:slug('writing'), backgroundStyle:'white', layout:'wide', eyebrow:'Writing / Thinking', title:'I write to make sense of what I notice.', body:block('Sometimes it becomes a blog post. Sometimes it becomes website copy, campaign messaging, a creative brief, or a small experiment. Writing helps me slow down, connect ideas, and turn scattered thoughts into something clearer.')},
      {_key:'contact', _type:'contactSection', isVisible:true, anchorId:slug('contact'), backgroundStyle:'ink', layout:'compact', eyebrow:'Contact', title:'Let’s connect', subtitle:'I’m interested in work that sits at the intersection of growth, storytelling, data, social impact, and practical digital systems.', showSocialLinks:true}
    ]
  },
  {_id:'project-growth', _type:'project', isVisible:true, title:'Growth & Performance Marketing', slug:slug('growth-performance-marketing'), category:'Growth', summary:'Campaign strategy, paid media optimization, lead generation, landing page improvement, and performance reporting.', proofPoints:['ROAS 12+ on Meta Ads','275% lead generation increase','300% lead generation increase','50% CPC reduction'], tools:['Meta Ads','Google Ads','GA4','Landing Page Optimization'], order:1},
  {_id:'project-content', _type:'project', isVisible:true, title:'Website, Product & Content Strategy', slug:slug('website-product-content-strategy'), category:'Digital Strategy', summary:'Website copy, SEO content, value proposition, go-to-market strategy, sitemaps, wireframes, and conversion-focused landing pages.', proofPoints:['SEO-friendly copy','Conversion journey mapping','Cross-functional briefs'], tools:['SEO','Wireframe','Content Strategy'], order:2},
  {_id:'project-analytics', _type:'project', isVisible:true, title:'Analytics, Tracking & Funnel Improvement', slug:slug('analytics-tracking-funnel-improvement'), category:'Analytics', summary:'Turning analytics, campaign data, and user behavior into recommendations for better decisions.', proofPoints:['Funnel analysis','Tracking setup','Dashboard thinking'], tools:['GA4','GTM','Microsoft Clarity','Looker','Sheets'], order:3},
  {_id:'exp-lead', _type:'experience', isVisible:true, role:'Digital Marketing Lead', company:'PT Maju Digital Bangun Indonesia / Goesdigital', startDate:'2023-12-01', endDate:'2025-07-01', summary:'Led and executed multi-brand digital marketing strategies across paid ads, SEO, website copy, analytics, creative direction, and campaign optimization.', impact:['ROAS 12+ on Meta Ads','4,700% increase in pre-registration clicks','Improved website engagement contributing to new client acquisition'], order:1},
  {_id:'exp-specialist', _type:'experience', isVisible:true, role:'Digital Marketing Specialist', company:'PT Maju Digital Bangun Indonesia / Goesdigital', startDate:'2023-07-01', endDate:'2023-11-01', summary:'Managed Google Ads and Meta Ads campaigns, improved landing pages, wrote SEO-friendly website copy, and developed go-to-market strategies.', impact:['275% increase in lead generation','50% CPC reduction within one month','117% LinkedIn follower increase'], order:2},
  {_id:'exp-bithour', _type:'experience', isVisible:true, role:'Digital Marketing — Lead Generation', company:'Bithour Production', startDate:'2023-01-01', endDate:'2023-04-01', summary:'Worked with the CEO on campaign strategy, performance analysis, business development, pitching, and client coordination.', impact:['300% lead generation increase within one month','Supported long-term yearly project contract'], order:3},
  {_id:'exp-sdgs', _type:'experience', isVisible:true, role:'Program & Project Assistant', company:'SDGs Hub UI', startDate:'2021-02-01', endDate:'2022-12-01', summary:'Supported project management, research, coordination, reporting, content production, and program delivery for SDGs-related initiatives.', impact:['67% organic follower increase','Facilitator for Environmental Pillar of Australia–Indonesia BRIDGE School Partnership Program'], order:4},
  {_id:'skill-growth', _type:'skillCategory', isVisible:true, title:'Growth & Performance', skills:['Meta Ads','Google Ads','Lead Generation','Campaign Optimization','Paid Media Strategy','CRO'], order:1},
  {_id:'skill-content', _type:'skillCategory', isVisible:true, title:'Content, SEO & Storytelling', skills:['Website Copy','SEO Content','Campaign Messaging','Content Strategy','Creative Briefs'], order:2},
  {_id:'skill-analytics', _type:'skillCategory', isVisible:true, title:'Analytics & Tracking', skills:['GA4','Google Tag Manager','Microsoft Clarity','Looker','Google Sheets','Excel','Funnel Analysis'], order:3},
  {_id:'skill-product', _type:'skillCategory', isVisible:true, title:'Product & Digital Strategy', skills:['Go-to-Market Strategy','Value Proposition','Business Model Canvas','Sitemap','Wireframe','Landing Page Journey'], order:4}
]

for (const doc of docs) {
  await client.createOrReplace(doc)
  console.log(`Seeded ${doc._type}: ${doc._id}`)
}
